CREATE TABLE "dataverse_tsv_metadata" (
        "id_m" SERIAL NOT NULL,
        "m_active" INT DEFAULT 1 NOT NULL,
        "m_schema" INT DEFAULT 0 NOT NULL,
        "m_name" VARCHAR(200) NOT NULL,
        "m_title" VARCHAR(200) NOT NULL,
        "m_description" TEXT NOT NULL,
        "m_watermark" VARCHAR(200) NOT NULL,
        "m_fieldType" VARCHAR(200) NOT NULL,
        "m_displayOrder" INT DEFAULT 0 NOT NULL,
        "m_displayFormat" VARCHAR(200) NOT NULL,
        "m_advancedSearchField" INT DEFAULT 0 NOT NULL,
        "m_allowControlledVocabulary" INT DEFAULT 0 NOT NULL,
        "m_allowmultiples" INT DEFAULT 0 NOT NULL,
        "m_facetable" INT DEFAULT 0 NOT NULL,
        "m_displayoncreate" INT DEFAULT 0 NOT NULL,
        "m_required" INT DEFAULT 0 NOT NULL,
        "m_parent" VARCHAR(80) NOT NULL,
        "metadatablock_id" VARCHAR(80) NOT NULL,
        "m_termURI" VARCHAR(200) NOT NULL,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        CONSTRAINT "pk_dataverse_tsv_metadata" PRIMARY KEY("id_m"));
