<h2>HISTÓRICO </h2>
<p>O repositório LattesData foi concebido no âmbito do Compromisso 3 do 4º Plano de Ação Nacional em Governo Aberto, que visava estabelecer mecanismos de governança de dados científicos para o avanço da Ciência Aberta no Brasil. Para seu desenvolvimento, em dezembro de 2019, foi firmado um Acordo de Cooperação entre o Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq) e o Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict).</p>
<p>Posteriormente, foram estabelecidas atribuições e responsabilidades de atuação conjunta de ambas as instituições, visando à colaboração para o desenvolvimento da Ciência Aberta no Brasil. A parceria encarregou-se, entre outros, da definição da arquitetura de informação do repositório, da elaboração de sua política, dos termos de depósitos dos datasets em sua estrutura, a da definição dos conjuntos de metadados descritores dos datasets nele depositados.</p>
<p>Com o objetivo de garantir a governança dos dados depositados, um Acordo de Cooperação Internacional foi assinado com a organização DataCite, visando a atribuição de identificadores DOI (Digital Object Identifier) aos datasets no momento de seu depósito. O custo de emissão e atribuição dos DOIs aos dados depositados no LattesData é arcado pelo CNPq, não havendo ônus algum para os pesquisadores depositantes.</p>
<p>O repositório tem por principais metas:
<ul>
    <li aria-level="1">Estimular o avanço da prática da Ciência Aberta no Brasil, contribuindo para o estabelecimento de acervo de dados de pesquisa em infraestrutura nacional seguindo os princípios FAIR para dados (Findable - Localizáveis; Accessible - Acessíveis; Interoperable - Interoperáveis; Reusable - Reutilizáveis);</li>
    <li aria-level="1">Armazenar os dados de pesquisa de modo a manter sua preservação e acessibilidade no longo prazo;</li>
    <li aria-level="1">Estimular o reuso de dados de pesquisa, contribuindo assim para redução de custos de novos projetos de pesquisa.</li>
</ul>
</p>
<p>O LattesData contou com a participação de diversos profissionais durante o seu desenvolvimento, os quais foram imprescindíveis para o seu avanço. Destaca-se a extraordinária contribuição do Professor Doutor Rene Faustino Gabriel Junior, da Universidade Federal do Rio Grande do Sul (UFRGS), que, como pesquisador, não mediu esforços para que o projeto tornasse realidade, rumo ao avanço da Ciência Aberta no Brasil.</p>
<div style="height: 20px; width: 100%;"></div>